// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hgskfjalecoqcqzngqso.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imhnc2tmamFsZWNvcWNxem5ncXNvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcxNzE3MjIsImV4cCI6MjA3Mjc0NzcyMn0.KsIN5l84hwszNjunv76t6aMYgZlfABYi_n40ngCTddI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});